version: '3.8'

services:
  web:
    build:
      context: .
    container_name: messaging_app_web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Make sure this is correct for your project structure
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: messaging_app.settings
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: gabi3slowmo
      MYSQL_PASSWORD: Shmurdaa3
      MYSQL_DATABASE: messaging_app_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: messaging_app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: messaging_app_db
      MYSQL_USER: gabi3slowmo
      MYSQL_PASSWORD: Shmurdaa3
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
