pipeline {
    agent any

    environment {
        GIT_REPO = 'https://github.com/Sand-raM/alx-backend-python.git'
        BRANCH = 'main'
        GITHUB_CREDENTIALS = 'github-credentials-id'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from GitHub using credentials
                git branch: 'main', credentialsId: "${GITHUB_CREDENTIALS}", url: "${GIT_REPO}"
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    // Install dependencies from the requirements.txt file
                    sh 'pip3 install -r messaging_app/requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    // Run pytest tests
                    sh 'pytest --maxfail=1 --disable-warnings -q'
                }
            }
        }

        stage('Generate Report') {
            steps {
                script {
                    // Generate test report with pytest
                    sh 'pytest --maxfail=1 --disable-warnings --html=report.html'
                }
            }
        }
    }
}
