pipeline {
    agent any

    environment {
        GIT_REPO = 'https://github.com/yourusername/alx-backend-python.git'
        BRANCH = 'main'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: "${BRANCH}", url: "${GIT_REPO}"
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    sh 'pytest --maxfail=1 --disable-warnings -q'
                }
            }
        }

        stage('Generate Report') {
            steps {
                script {
                    sh 'pytest --maxfail=1 --disable-warnings --html=report.html'
                }
            }
        }
    }
}
