name: Docker Image Deployment

on:
  push:
    branches:
      - main # Trigger this workflow on push events to the "main" branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment for the workflow

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Check out the code from the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Set up Docker Buildx to enable advanced build features

      - name: Log in to Docker Hub
        uses: docker/login-action@v2 # Log in to Docker Hub using credentials
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # GitHub Actions secret for Docker username
          password: ${{ secrets.DOCKER_PASSWORD }} # GitHub Actions secret for Docker password

      - name: Build and push Docker image
        uses: docker/build-push-action@v4 # Build and push the Docker image
        with:
          context: ./ # The directory containing the Dockerfile
          push: true # Push the image to the Docker registry
          tags: gabi3dev/messaging-app:latest # Replace with your Docker Hub username and image name
